# This is a basic workflow to help you get started with Actions

name: Fetch

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ver:
        description: 'Package Version'
        required: true
        default: 'latest'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Prepare Environment
        run: |
          sudo apt update
          sudo apt install php php-curl curl libnss3 nss-plugin-pem ca-certificates python3
          # Prepare curl-impersonate
          wget https://ghproxy.com/https://github.com/lwthiker/curl-impersonate/releases/download/v0.5.4/curl-impersonate-v0.5.4.x86_64-linux-gnu.tar.gz -O curl.tar.gz
          tar -xvf curl.tar.gz
          # Prepare UnityPy
          git clone https://ghproxy.com/https://github.com/K0lb3/UnityPy.git
          cd UnityPy
          python -m pip install .

      - name: Download Resource Package
        run: |
          ./curl_chrome110 --parallel --parallel-immediate --parallel-max 64 -L -k -C - -o Phigros.xapk https://d.apkpure.com/b/XAPK/com.PigeonGames.Phigros?version=${{ github.event.inputs.ver }}
          unzip Phigros.xapk
          unzip Android/obb/com.PigeonGames.Phigros/main.*.com.PigeonGames.Phigros.obb
          
      - name: Unpack Chart From Resource Package
        run: |
          python3 unpack.py
